services:
  rag-service:
    container_name: rag_service
    build: . 
    
    ports:
      # Maps host port 4545 to container port 4545
      - "4545:4545"
    network_mode: "host"
    volumes:
      - ./:/app
    
    environment:

      RAG_PORT: 4545
      RAG_GUNICORN_WORKERS: 2

      PYTHONDONTWRITEBYTECODE: 1
    
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
      
    # networks:
    #   - shared_app_network 
    dns:
      - 8.8.8.8
      - 8.8.4.4